### ISSUE TITLE
ENV_ variables usage

### ISSUE THREAD

**Issue by martzoukos** [contentful/jekyll-contentful-data-import#21]
Hello,

thanks for the great work in this tool.
I have a question regarding PR https://github.com/contentful/jekyll-contentful-data-import/pull/19, tried to set it up for a project of mine and I have this config set up: https://gist.github.com/martzoukos/1faece5f70e56ee57954d4116fce9bb4
and this `.env` file on my project's root folder: https://gist.github.com/martzoukos/1659a797ad15ff59d22bdb4f79f15be3
- When I'm running `jekyll contentful` I get a `jekyll 3.2.1 | Error:  Contentful::Unauthorized` error.
- If I replace the `ENV_CONTENTFUL_SPACE_ID` and `ENV_CONTENTFUL_ACCESS_TOKEN` in the config with their values, then the fetch works.
- I have `gem 'dotenv-rails'` in my gemfile

Is there something I'm missing in this setup?

Thank you in advance for your help.

**Comment by dlitvakb** [comment]
Hey @martzoukos,

`dotenv` will only work if you use a Rake command (like explained on the Caveats section of the Readme), this is because of how Jekyll itself works with external gems, so sadly that's not something I can help with.

To use it without `dotenv`, just add to your `.bashrc` or `.bash_profile` the following 2 lines:

```bash
export CONTENTFUL_ACCESS_TOKEN=abc123
export CONTENTFUL_SPACE_ID=abc123
```

Else, you can specify them when running the command like follows:

```bash
CONTENTFUL_ACCESS_TOKEN=abc123 CONTENTFUL_SPACE_ID=abc123 jekyll contentful
```

Sorry that Jekyll is so opinionated with some stuff

Hope that helps

Cheers

**Comment by martzoukos** [comment]
Hello @dlitvakb 

and thanks a lot for the quick reply! :)

That also works so I'll try that.

Thank you.

**Comment by jcbpl** [comment]
Any plans to cut a new gem release that would include #19?

**Comment by dlitvakb** [comment]
Hey @jcbpl,

Yes, this will be released on Monday after I return from my vacations

Cheers

**Comment by jcbpl** [comment]
@dlitvakb Awesome, thank you!
