### ISSUE TITLE
Delay Between Change and Import

### ISSUE THREAD

**Issue by jckfa** [contentful/jekyll-contentful-data-import#38]
If I publish a change on Contentful, it takes at least 20 seconds for `jekyll contentful` to yield that change in the resulting data file.

In production, my site is set up to build immediately after a change is made. This 20 second delay is a problem as the build process will finish well before `jekyll contentful` has a chance to update the data. I can delay the build 30 seconds before executing, but that's not ideal.

I understand this is probably an issue with the Contentful Content Delivery API, but I guess what I'm asking is... is this even an issue or just how the thing works? Pardon my ignorance.

**Comment by dlitvakb** [comment]
Hey @jckfa,

This is the expected behavior, after publishing a Resource in Contentful, the CDN that runs on top of our API has to do a cache clear of your whole space across the world, this might take anywhere from 5 seconds to 2 minutes depending on the amount of content that you have. Therefore, leading to your changes not visible until that process finishes.

If you're using Webhooks to trigger your builds, these fire immediately after content was published. So we advise to add a delay between the reception and the actual build job.

Hope that clarifies the situation.

Cheers

**Comment by jckfa** [comment]
@dlitvakb Thanks for the clarification.

**Comment by chriso0710** [comment]
Good point, which I happened to run into as well. 
So this means adding a fixed delay of 2 minutes before building jekyll to be completely safe? In my tests with small json datasets this never was needed. I mostly got the new data back in a few seconds.

Would it be possible to receive a webhook **after** the CDN cache was cleared?

**Comment by dlitvakb** [comment]
Hey @chriso0710,

Depending on the size of the dataset. Large datasets (over 100k entries) may take up over a minute. Smaller datasets only take a couple of seconds.

Sadly the Webhook stack and the CDN are totally disconnected from one another. Therefore, client side delays must be enforced.

**Comment by chriso0710** [comment]
Thanks @dlitvakb. I will start with a build delay of 60 secs...
