### ISSUE TITLE
Locales missing in yaml file

### ISSUE THREAD

**Issue by nilsborg** [contentful/jekyll-contentful-data-import#60]
Hi there!

just grabbed this great gem and added it to our Jekyll project. 

I got content in contentful translated in 2 locales but only get the default locale in the content import..

Anyone else got this and knows what to do?

**Comment by dlitvakb** [comment]
Hi @nilsborg,

In the `cda_query` [option](https://github.com/contentful/jekyll-contentful-data-import#configuration), you can specify `locale: '*'` that will retrieve all locales, otherwise only the default locale will be returned.

You can learn more about how localization works [here](https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/localization).

Cheers
