### ISSUE TITLE
Documentation/Example: Jekyll collections

### ISSUE THREAD

**Issue by Jan10** [contentful/jekyll-contentful-data-import#65]
Can you give an example of "how to use the importer with jekyll collections"?
I want to automatically create pages for each contetnful entry.

https://jekyllrb.com/docs/collections/

Thanks!

**Comment by dlitvakb** [comment]
Hey @Jan10,

This tool uses instead of collections, data files, you can find the docs [here](https://jekyllrb.com/docs/datafiles/).

While, not exactly the same, the usage is very similar. You can use something like `https://github.com/avillafiorita/jekyll-datapage_gen` to generate the pages out of data files.

Cheers
